# Generated by Django 4.2.1 on 2023-07-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.PositiveIntegerField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Идентификатор товара",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Наименование товара"
                    ),
                ),
                ("price", models.IntegerField(verbose_name="Цена товара")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="photos/%Y/%m/%d/",
                        verbose_name="Фото товара",
                    ),
                ),
                ("release_date", models.DateField(verbose_name="Дата добавления")),
                (
                    "lte_exists",
                    models.BooleanField(
                        default=False, verbose_name="Наличие функции LTE"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=150, unique=True, verbose_name="URL товара"
                    ),
                ),
            ],
            options={
                "verbose_name": "Телефон",
                "verbose_name_plural": "Телефоны",
            },
        ),
    ]
