# Generated by Django 4.2.1 on 2023-07-03 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("phones", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="phone",
            options={},
        ),
    ]
